
//MIT License
//
//Copyright (c) 2023 bluetailtech
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
//
//


package btconfig;

/**
 *
 * @author radioactive
 */
public class aliasEntry extends javax.swing.JFrame {
  Alias alias;
  int rid_int;

    /**
     * Creates new form aliasEntry
     */
    public aliasEntry(Alias a) {
      initComponents();
      alias = a;
    }

    public void setRID(int ridval) {
      if(isVisible()) return;

      rid_int =ridval;
      rid.setText("RID: "+Integer.valueOf(ridval).toString());
      alias.findAlias(this,ridval);
      alias_txt.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rid = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        alias_txt = new javax.swing.JTextField();

        setTitle("Alias Entry");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alias_txtKeyTyped(evt);
            }
        });
        jPanel1.add(cancel);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alias_txtKeyTyped(evt);
            }
        });
        jPanel1.add(ok);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        rid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rid.setText("RID");
        jPanel3.add(rid);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Alias");
        jPanel4.add(jLabel2);

        alias_txt.setColumns(15);
        alias_txt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        alias_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alias_txtKeyTyped(evt);
            }
        });
        jPanel4.add(alias_txt);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setAlias(String alias_str) {
      alias_txt.setText(alias_str);
    }

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      rid.setText("RID:");
      alias_txt.setText("");
      setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
      if(rid_int!=0) {
        alias.setAlias(this, rid_int, alias_txt.getText().trim());
      }
      alias_txt.setText("");
      setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    private void alias_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alias_txtKeyTyped
      if( evt.getKeyChar() == '\n' ) {
        if(rid_int!=0) {
          alias.setAlias(this, rid_int, alias_txt.getText().trim());
        }
        alias_txt.setText("");
        setVisible(false);
      }
      if( evt.getKeyChar() == '\033' ) {
        alias_txt.setText("");
        setVisible(false);
      }
    }//GEN-LAST:event_alias_txtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alias_txt;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton ok;
    private javax.swing.JLabel rid;
    // End of variables declaration//GEN-END:variables
}
